export const ACCIONES_AUDITORIA = {
  CREAR_USUARIO: "CREAR_USUARIO",
  ACTUALIZAR_USUARIO: "ACTUALIZAR_USUARIO",
  ELIMINAR_USUARIO: "ELIMINAR_USUARIO",
  RESETEAR_CONTRASEÑA_EMAIL: "RESETEAR_CONTRASEÑA_EMAIL",
  GENERAR_CONTRASEÑA: "GENERAR_CONTRASEÑA",

  CREAR_PLAZA: "CREAR_PLAZA",
  ACTUALIZAR_PLAZA: "ACTUALIZAR_PLAZA",
  ELIMINAR_PLAZA: "ELIMINAR_PLAZA",

  CREAR_SOLICITUD: "CREAR_SOLICITUD",
  APROBAR_SOLICITUD: "APROBAR_SOLICITUD",
  RECHAZAR_SOLICITUD: "RECHAZAR_SOLICITUD",
  MARCAR_ENTREVISTA_PASADA: "MARCAR_ENTREVISTA_PASADA",
  MARCAR_ENTREVISTA_RECHAZADA: "MARCAR_ENTREVISTA_RECHAZADA",
  CITAR_CANDIDATO: "CITAR_CANDIDATO",
  ACTUALIZAR_CITA: "ACTUALIZAR_CITA",
  CONTRATAR_DESDE_RESERVA: "CONTRATAR_DESDE_RESERVA",
  DENEGAR_DESDE_RESERVA: "DENEGAR_DESDE_RESERVA",
  CITAR_DESDE_RESERVA: "CITAR_DESDE_RESERVA",

  CREAR_CANDIDATO: "CREAR_CANDIDATO",
  ACTUALIZAR_CANDIDATO: "ACTUALIZAR_CANDIDATO",

  CREAR_EVALUACION: "CREAR_EVALUACION",
  ACTUALIZAR_EVALUACION: "ACTUALIZAR_EVALUACION",

  INTENTO_LOGIN_FALLIDO: "INTENTO_LOGIN_FALLIDO",
} as const;

export type AccionAuditoria = (typeof ACCIONES_AUDITORIA)[keyof typeof ACCIONES_AUDITORIA];

export const ENTIDADES_AUDITORIA = {
  USUARIO: "Usuario",
  PLAZA: "Plaza",
  SOLICITUD: "Solicitud",
  CANDIDATO: "Candidato",
  CITA: "Cita",
  EVALUACION: "Evaluacion",
  SISTEMA: "Sistema",
} as const;
